services:
  - type: web
    name: manify-pwa
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /sw.js
        name: Cache-Control
        value: no-cache
